/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionColumn: typeof import('./src/components/ActionColumn.vue')['default']
    ActionsLayout: typeof import('./src/components/ActionsLayout.vue')['default']
    ButtonArea: typeof import('./src/components/ButtonArea.vue')['default']
    CreateNew: typeof import('./src/components/events/CreateNew.vue')['default']
    EditAttributes: typeof import('./src/components/events/EditAttributes.vue')['default']
    EditFinished: typeof import('./src/components/events/EditFinished.vue')['default']
    EventBookings: typeof import('./src/components/events/EventBookings.vue')['default']
    EventListItem: typeof import('./src/components/EventListItem.vue')['default']
    EventSelection: typeof import('./src/components/EventSelection.vue')['default']
    EventTypeSelection: typeof import('./src/components/EventTypeSelection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnpaidBookings: typeof import('./src/components/events/UnpaidBookings.vue')['default']
  }
}
