/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/actions/bookings': RouteRecordInfo<'/actions/bookings', '/actions/bookings', Record<never, never>, Record<never, never>>,
    '/actions/deploy': RouteRecordInfo<'/actions/deploy', '/actions/deploy', Record<never, never>, Record<never, never>>,
    '/actions/email': RouteRecordInfo<'/actions/email', '/actions/email', Record<never, never>, Record<never, never>>,
    'default_action': RouteRecordInfo<'default_action', '/actions/events', Record<never, never>, Record<never, never>>,
    '/actions/payments': RouteRecordInfo<'/actions/payments', '/actions/payments', Record<never, never>, Record<never, never>>,
    '/actions/prebooking': RouteRecordInfo<'/actions/prebooking', '/actions/prebooking', Record<never, never>, Record<never, never>>,
  }
}
