/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, never>
    '/actions/bookings': RouteRecordInfo<
      '/actions/bookings',
      '/actions/bookings',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/actions/deploy': RouteRecordInfo<
      '/actions/deploy',
      '/actions/deploy',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/actions/email': RouteRecordInfo<
      '/actions/email',
      '/actions/email',
      Record<never, never>,
      Record<never, never>,
      never
    >
    default_action: RouteRecordInfo<
      'default_action',
      '/actions/events',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/actions/payments': RouteRecordInfo<
      '/actions/payments',
      '/actions/payments',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/actions/prebooking': RouteRecordInfo<
      '/actions/prebooking',
      '/actions/prebooking',
      Record<never, never>,
      Record<never, never>,
      never
    >
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/actions/bookings.vue': {
      routes: '/actions/bookings'
      views: never
    }
    'src/pages/actions/deploy.vue': {
      routes: '/actions/deploy'
      views: never
    }
    'src/pages/actions/email.vue': {
      routes: '/actions/email'
      views: never
    }
    'src/pages/actions/events.vue': {
      routes: 'default_action'
      views: never
    }
    'src/pages/actions/payments.vue': {
      routes: '/actions/payments'
      views: never
    }
    'src/pages/actions/prebooking.vue': {
      routes: '/actions/prebooking'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}
